## database setting
database:
  host: "localhost"
  port: "3306"
  user: "root"
  pass: "password"
  db: "db"
## enter server name.pg or lgw.you entered name,please reload server.[/reload confirm]
server: "none"